# Official image for Hashicorp's Terraform. It uses light image which is Alpine
# based as it is much lighter.
#
# Entrypoint is also needed as image by default set `terraform` binary as an
# entrypoint.
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan
  TF_VAR_FILE: test.tf-test
  BUILD_PATH: /builds/datadarius/tf-aks/bootstrap-azure-remote-state

cache:
  paths:
    - .terraform

before_script:
  - export ARM_CLIENT_ID=$client_id && export ARM_CLIENT_SECRET=$client_secret && export ARM_TENANT_ID=$tenant_id && export ARM_SUBSCRIPTION_ID=$subscription_id
  - export AZURE_CLIENT_ID=$client_id && AZURE_CLIENT_SECRET=$client_secret && AZURE_TENANT_ID=$tenant_id && export AZURE_SUBSCRIPTION_ID=$subscription_id
  - pwd
  - cd $BUILD_PATH
  - terraform --version
  - terraform init
  - ls -las
  
stages:
  - validate
  - plan
  - apply
  - inspec_test
  - destroy

validate:
  stage: validate
  script:
    - pwd
    - terraform validate -var-file=$TF_VAR_FILE -input=false

plan:
  stage: plan
  script:
    - pwd
    - terraform plan -var-file=$TF_VAR_FILE -input=false -out=$PLAN
    - ls
  artifacts:
    name: $PLAN
    paths:
      - $BUILD_PATH

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - pwd
    - ls
    - terraform apply -input=false $PLAN
  only:
    - master

inspec_test:
  stage: inspec_test
  script:
    - 'echo gem: --no-document > $HOME/.gemrc'
    - apk update
    - apk add build-base git libffi-dev ruby-dev ruby-bundler
    - gem install inspec
    - inspec exec my-profile -t azure://$AZURE_TENANT_ID
    - terraform destroy -input=false
