# Official image for Hashicorp's Terraform. It uses light image which is Alpine
# based as it is much lighter.
#
# Entrypoint is also needed as image by default set `terraform` binary as an
# entrypoint.
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan
  TF_STATE: terraform.tfstate
  TF_VAR_FILE: test.tf-test
  BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE: /builds/datadarius/tf-aks/bootstrap-azure-remote-state

cache:
  paths:
    - $BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE/.terraform

before_script:
  # secret vars required to talk to Azure via TF
  - export ARM_CLIENT_ID=$client_id && export ARM_CLIENT_SECRET=$client_secret && export ARM_TENANT_ID=$tenant_id && export ARM_SUBSCRIPTION_ID=$subscription_id
  # secret vars required to talk to Azure via inspec
  - export AZURE_CLIENT_ID=$client_id && AZURE_CLIENT_SECRET=$client_secret export && AZURE_TENANT_ID=$tenant_id && export AZURE_SUBSCRIPTION_ID=$subscription_id 
  - terraform --version
  - terraform init
  
stages:
  - validate
  - plan
  - apply
  - destroy
  - deploy
  - inspec_test

validate-bootstrap-azure-remote-state:
  stage: validate
  script:
    - cd $BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE
    - terraform validate -var-file=$TF_VAR_FILE -input=false

plan-bootstrap-azure-remote-state:
  stage: plan
  script:
    - cd $BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE
    - terraform plan -var-file=$TF_VAR_FILE -input=false -out=$PLAN
  artifacts:
    name: $PLAN
    paths:
      - $BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE


apply-bootstrap-azure-remote-state:
  stage: apply
  dependencies:
    - plan-bootstrap-azure-remote-state
  script:
    - cd $BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE
    - terraform apply -input=false $PLAN
    - ls *.tfstate
  artifacts:
    name: $TFSTATE
    paths:
      - $BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE
  only:
    - master

destroy-bootstrap-azure-remote-state:
  stage: destroy
  dependencies:
    - apply-bootstrap-azure-remote-state
  script:
  - $BUILD_PATH_BOOTSTRAP_AZURE_REMOTE_STATE  
  - terraform destroy -var-file=$TF_VAR_FILE -input=false -force
  only:
    - master

# deploy:
#   environment:
#     name: production
#   dependencies:
#     - plan
#   only:
#   - master
#   when: manual


#TODO move inspec binaries into dedicated image.
#inspec_test:
#  stage: inspec_test
#  dependencies:
#    - deploy
#  only:
#    - master
#  script:
#    - 'echo gem: --no-document > $HOME/.gemrc'
#    - apk update
#    - apk add build-base git libffi-dev ruby-dev ruby-bundler
#    - gem install inspec
#    - inspec exec inspec-profile -t azure://

